### ISSUE TITLE
Error "Unable to locate package php7.0"

### ISSUE THREAD

**Issue by apacheservices68** [vietdien2005/fullstack-jenkins#1]
When I run docker compose . I received an error message `E: Unable to locate package php7.0
E: Couldn't find any package by regex 'php7.0'
E: Unable to locate package php7.0-cli
E: Couldn't find any package by regex 'php7.0-cli'
E: Unable to locate package php7.0-cg
E: Couldn't find any package by regex 'php7.0-cgi'
E: Unable to locate package php7.0-common
E: Couldn't find any package by regex 'php7.0-common'
E: Unable to locate package php7.0-curl
E: Couldn't find any package by regex 'php7.0-curl'
E: Unable to locate package php7.0-dba
E: Couldn't find any package by regex 'php7.0-dba'
E: Unable to locate package php7.0-dev
E: Couldn't find any package by regex 'php7.0-dev'
E: Unable to locate package php7.0-fpm
E: Couldn't find any package by regex 'php7.0-fpm'
E: Unable to locate package php7.0-gd
E: Couldn't find any package by regex 'php7.0-gd'
E: Unable to locate package php7.0-gmp
E: Couldn't find any package by regex 'php7.0-gmp'
E: Unable to locate package php7.0-imap
E: Couldn't find any package by regex 'php7.0-imap'
E: Unable to locate package php7.0-intl
E: Couldn't find any package by regex 'php7.0-intl'
E: Unable to locate package php7.0-json
E: Couldn't find any package by regex 'php7.0-json'
E: Unable to locate package php7.0-mbstring
E: Couldn't find any package by regex 'php7.0-mbstring'
E: Unable to locate package php7.0-mcrypt
E: Couldn't find any package by regex 'php7.0-mcrypt'
E: Unable to locate package php7.0-mysql
E: Couldn't find any package by regex 'php7.0-mysql'
E: Unable to locate package php7.0-odbc
E: Couldn't find any package by regex 'php7.0-odbc'
E: Unable to locate package php7.0-opcache
E: Couldn't find any package by regex 'php7.0-opcache'
E: Unable to locate package php7.0-pgsql
E: Couldn't find any package by regex 'php7.0-pgsql'
E: Unable to locate package php7.0-pspell
E: Couldn't find any package by regex 'php7.0-pspell'
E: Unable to locate package php7.0-readline
E: Couldn't find any package by regex 'php7.0-readline'
E: Unable to locate package php7.0-recode
E: Couldn't find any package by regex 'php7.0-recode'
E: Unable to locate package php7.0-sqlite3
E: Couldn't find any package by regex 'php7.0-sqlite3'
E: Unable to locate package php7.0-tidy
E: Couldn't find any package by regex 'php7.0-tidy'
E: Unable to locate package php7.0-xml
E: Couldn't find any package by regex 'php7.0-xml'
E: Unable to locate package php7.0-xmlrpc
E: Couldn't find any package by regex 'php7.0-xmlrpc'
E: Unable to locate package php7.0-xsl
E: Couldn't find any package by regex 'php7.0-xsl'
E: Unable to locate package php7.0-zip
E: Couldn't find any package by regex 'php7.0-zip'
ERROR: Service 'jenkins' failed to build: The command '/bin/sh -c apt-get update && apt-get -y install php7.0 php7.0-cli php7.0-cgi php7.0-common php7.0-curl php7.0-dba php7.0-dev     php7.0-fpm php7.0-gd php7.0-gmp php7.0-imap php7.0-intl php7.0-json php7.0-mbstring php7.0-mcrypt php7.0-mysql     php7.0-odbc php7.0-opcache php7.0-pgsql php7.0-pspell php7.0-readline php7.0-recode php7.0-sqlite3 php7.0-tidy     php7.0-xml php7.0-xmlrpc php7.0-xsl php7.0-zip' returned a non-zero code: 100
`

**Comment by vietdien2005** [comment]
I fixed, let's build again. If you have any problems check in my travisCI. Thanks 
[TravisCI](https://travis-ci.org/vietdien2005/fullstack-jenkins)
